// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw1F50QQD6mF4t-FJqNrFvKssayeJ7Hsk',
    appId: '1:3200679104:web:a4f9ccc209967f2473c125',
    messagingSenderId: '3200679104',
    projectId: 'auth-modul-lucky',
    authDomain: 'auth-modul-lucky.firebaseapp.com',
    storageBucket: 'auth-modul-lucky.firebasestorage.app',
    measurementId: 'G-190Z2HGGMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcE2z3U8GbKxFqTpLBnVkxlJVT4pZxANw',
    appId: '1:3200679104:android:d73275dcada9c09973c125',
    messagingSenderId: '3200679104',
    projectId: 'auth-modul-lucky',
    storageBucket: 'auth-modul-lucky.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeYacZIKsGAkggQNT2jKsWBrL4Kxo5_UI',
    appId: '1:3200679104:ios:be0f6cb5fa3260bb73c125',
    messagingSenderId: '3200679104',
    projectId: 'auth-modul-lucky',
    storageBucket: 'auth-modul-lucky.firebasestorage.app',
    iosBundleId: 'com.example.studyFirebaseV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeYacZIKsGAkggQNT2jKsWBrL4Kxo5_UI',
    appId: '1:3200679104:ios:be0f6cb5fa3260bb73c125',
    messagingSenderId: '3200679104',
    projectId: 'auth-modul-lucky',
    storageBucket: 'auth-modul-lucky.firebasestorage.app',
    iosBundleId: 'com.example.studyFirebaseV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw1F50QQD6mF4t-FJqNrFvKssayeJ7Hsk',
    appId: '1:3200679104:web:0fd7f6a3e4f12dd473c125',
    messagingSenderId: '3200679104',
    projectId: 'auth-modul-lucky',
    authDomain: 'auth-modul-lucky.firebaseapp.com',
    storageBucket: 'auth-modul-lucky.firebasestorage.app',
    measurementId: 'G-N975B1SJZ6',
  );
}
